name: hello

on:
  push:

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Executing
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "I'm here"
          secret="$(echo $SECRET_KEY)"
          echo "Here I am ${secret}"
