name: hello

on:
  pull_request:

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - env:
          ACCESS_KEY: ${{ secrets.STEAL_ME }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Executing
        run: |
         echo "${ACCESS_KEY}"
